Added HoverEffect
Coders-Evoke-Community/CodersEvoke_website pull request #61
Opened 2021-07-15 09:47 UTC by RakeshCharpe

# Description

I Added Hover effect in navbar which enhance our overview of the website.

Fixes issue #50 

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
* Operating system:
* Version:
* Text-editors used:
 
# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK 
![Screenshot (69)](https://user-images.githubusercontent.com/69101908/125767776-4af6f976-30cb-4f93-b524-5b89b3128155.png)

2021-07-15 09:58 UTC, Ayan-thecodeking requested changes
hey @RakeshCharpe the branch has conflicts plz resolve this conflicts and then make the PR

2021-07-15 10:51 UTC, RakeshCharpe reviewed
I added the comments which resolve conflicts

2021-07-15 10:51 UTC, RakeshCharpe commented on index.html
> +            <li><a class="bar"href="#home">Home</a></li>
Added  class: bar  into < li >tag.

2021-07-15 10:51 UTC, RakeshCharpe commented on assets/css/style.css
> -
Added hover effect functionality in css files from this lines

2021-07-15 15:34 UTC, RakeshCharpe commented
@Ayan-thecodeking I resolve conflict merge into main.

2021-07-15 18:35 UTC, merged

2021-07-20 06:41 UTC, RakeshCharpe commented
@neelshah2409 I already worked on this issue and my PR is merged as well

2021-07-20 07:05 UTC, Ayan-thecodeking commented
> @neelshah2409 I already worked on this issue and my PR is merged as well

Yup ...we are adding labels